server.port=8090

# Database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-mute-sunset-axd586xn-pooler.c-4.us-east-2.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Z1ANR5kbfcon

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Encoding
spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

# Uploads
upload.dir=images